# -*- mode: python ; coding: utf-8 -*-
"""
TwinStar Quantum EXE 빌드 스펙 파일
"""

import os

block_cipher = None
PROJECT_ROOT = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['GUI/staru_main.py'],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=[
        # GUI 리소스
        ('GUI/assets', 'GUI/assets'),
        
        # 설정 및 프리셋
        ('config/presets', 'config/presets'),
        ('api_key_config_template.json', '.'),
        ('GUI/styles.qss', 'GUI'),
        
        # 다국어 파일
        ('locales', 'locales'),
        
        # 버전 파일
        ('version.txt', '.'),
        ('version.json', '.'),
    ],
    hiddenimports=[
        'GUI',
        'GUI.backtest_result_widget',
        'GUI.backtest_widget',
        'GUI.bot_status_widget',
        'GUI.cache_manager_widget',
        'GUI.candle_aggregator',
        'GUI.capital_management_widget',
        'GUI.capital_manager',
        'GUI.chart_items',
        'GUI.constants',
        'GUI.crypto_manager',
        'GUI.dashboard_widgets',
        'GUI.data_collector_widget',
        'GUI.data_download_widget',
        'GUI.data_loader',
        'GUI.data_manager',
        'GUI.developer_mode_widget',
        'GUI.enhanced_chart_widget',
        'GUI.exchange_selector_widget',
        'GUI.glossary_popup',
        'GUI.help_dialog',
        'GUI.help_popup',
        'GUI.help_widget',
        'GUI.history_widget',
        'GUI.i18n',
        'GUI.indicator_generator',
        'GUI.live_trading_manager',
        'GUI.login',
        'GUI.login_dialog',
        'GUI.multi_system_widget',
        'GUI.notification_manager',
        'GUI.notification_widget',
        'GUI.nowcast_widget',
        'GUI.onboarding_dialog',
        'GUI.optimization_widget',
        'GUI.payment_dialog',
        'GUI.pc_license_dialog',
        'GUI.position_widget',
        'GUI.register_dialog',
        'GUI.security',
        'GUI.settings_widget',
        'GUI.staru_main',
        'GUI.strategy_interface',
        'GUI.strategy_selector_widget',
        'GUI.styles',
        'GUI.symbol_cache',
        'GUI.telegram_popup',
        'GUI.telegram_settings_widget',
        'GUI.tier_popup',
        'GUI.trade_chart_dialog',
        'GUI.trade_detail_popup',
        'GUI.trade_executor',
        'GUI.trading_dashboard',
        'GUI.update_popup',
        'GUI.websocket_manager',
        'OpenSSL',
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.sip',
        '__future__',
        '_distutils_hack',
        '_imp',
        '_ssl',
        'aiohttp',
        'binance',
        'binance.client',
        'binance.enums',
        'bot_bybit',
        'bot_status',
        'calendar',
        'capital_config',
        'ccxt',
        'collections',
        'colorsys',
        'compileall',
        'config_bybit',
        'constants',
        'core',
        'core.__init__',
        'core.crypto_payment',
        'core.dual_track_trader',
        'core.license_guard',
        'core.multi_backtest',
        'core.multi_optimizer',
        'core.multi_sniper',
        'core.optimizer',
        'core.preset_health',
        'core.strategy_core',
        'core.unified_bot',
        'core.updater',
        'crypto_manager',
        'crypto_utils',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.primitives.ciphers.aead',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'data_manager',
        'datetime',
        'distutils',
        'docutils',
        'dotenv',
        'encodings',
        'encodings.cp949',
        'encodings.euc_kr',
        'encodings.utf_8',
        'error_guide',
        'exchange_selector_widget',
        'exchanges',
        'exchanges.base_exchange',
        'exchanges.binance_exchange',
        'exchanges.bingx_exchange',
        'exchanges.bitget_exchange',
        'exchanges.bithumb_exchange',
        'exchanges.bybit_exchange',
        'exchanges.ccxt_exchange',
        'exchanges.exchange_manager',
        'exchanges.lighter_exchange',
        'exchanges.okx_exchange',
        'exchanges.upbit_exchange',
        'exchanges.ws_handler',
        'final_causal_strategy',
        'flask',
        'getopt',
        'getpass',
        'hashlib',
        'history_widget',
        'indicator_generator',
        'ipaddress',
        'jinja2',
        'json',
        'license_manager',
        'license_tiers',
        'lighter',
        'locales',
        'logging',
        'logging.handlers',
        'marshal',
        'matplotlib',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.pyplot',
        'mimetypes',
        'notification_manager',
        'ntlm',
        'numpy',
        'numpy.core',
        'optimization_widget',
        'optimizer',
        'optparse',
        'os',
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'pandas_ta',
        'pathlib',
        'paths',
        'payment_dialog',
        'pip',
        'pkg_resources',
        'platform',
        'plistlib',
        'pprint',
        'preset_manager',
        'py_compile',
        'pyarrow',
        'pybit',
        'pybit.unified_trading',
        'pybithumb',
        'pyparsing',
        'pyqtgraph',
        'pyupbit',
        'queue',
        'railroad',
        'register_dialog',
        'reprlib',
        'requests',
        'runpy',
        'scalping_5m_strategy',
        'scipy',
        'secure_storage',
        'select',
        'setuptools',
        'shlex',
        'site',
        'sklearn',
        'smc_utils',
        'sphinx',
        'storage.secure_storage',
        'storage.state_storage',
        'storage.trade_history',
        'storage.trade_storage',
        'strategies',
        'strategy_1h',
        'strategy_alpha_g',
        'strategy_alpha_h',
        'strategy_alpha_ict',
        'strategy_alpha_k',
        'strategy_alpha_l',
        'strategy_alpha_l_mtf',
        'strategy_alpha_l_plus',
        'strategy_alpha_s',
        'strategy_alpha_v',
        'strategy_alpha_w',
        'strategy_alpha_y',
        'strategy_breakeven',
        'strategy_breakeven_v2',
        'strategy_core',
        'strategy_smc_exit',
        'strategy_x7_mtf',
        'strategy_x7_plus',
        'sys',
        'system_doctor',
        'ta',
        'telegram',
        'telegram.ext',
        'telegram_notifier',
        'threading',
        'time',
        'trade_chart_dialog',
        'trading_dashboard',
        'trading_safety',
        'unified_bot',
        'urllib3',
        'user_guide',
        'utils.data_manager',
        'utils.preset_manager',
        'uuid',
        'webbrowser',
        'websocket',
        'websocket._core',
        'websockets',
        'winreg',
        'xmlrpc',
        'yaml',
        'zipimport',
        # Custom GUI modules without prefix
        'trading_dashboard', 'backtest_widget', 'history_widget', 'settings_widget',
        'data_collector_widget', 'optimization_widget', 'dashboard_widgets',
        
        'utils', 'utils.bot_data_utils', 'utils.data_utils',
        
        # pycryptodome (암호화)
        'Crypto', 'Crypto.Cipher', 'Crypto.Cipher.AES',
        'Crypto.Util', 'Crypto.Util.Padding',
        
        # strategies
        'strategies',
        'strategies.strategy_loader',
        'strategies.wm_pattern_strategy',
        'strategies.parameter_optimizer',
        'strategies.example_strategy',
        
        # locales (다국어)
        'locales', 'locales.lang_manager',
        
        # license
        'license_tiers',
        
        # 멀티 트레이더 (Phase 4)
        'core.multi_trader', 'core.multi_sniper',
        'utils.symbol_converter',
        'GUI.multi_session_popup', 'GUI.sniper_session_popup',
        
        # 누락된 모듈 추가 (2025-12-22)
        'core.auto_optimizer',
        'utils.time_utils',
        'utils.cache_cleaner',
        'utils.error_reporter',
        'utils.api_utils',
        'utils.data_utils',
        'utils.preset_manager',
        'utils.new_coin_detector',
        'exchanges.exchange_manager',
        # 누락된 모듈 대거 추가 (check_spec_full.py 기반)
        'GUI.debug_dashboard',
        'GUI.debug_import_gui',
        'GUI.test_history_widget',
        'GUI.verify_all_modules',
        'core.chart_matcher',
        'utils.chart_profiler',
        'utils.data_downloader',
        'utils.preset_storage',
        'sqlalchemy',
        'orjson',
        'sqlalchemy.sql.default_comparator', # sqlalchemy 필수 서브모듈
        'sqlite3',
        'dataclasses',
        'utils.helpers',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'IPython', 'jupyter', 'pytest', 'test', '_backup_2025', 'dist', 'build', '*.log', '*.parquet', '.env', 'node_modules', '.venv'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name='TwinStar_Quantum',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon='GUI/assets/icon.ico',
)

coll = COLLECT(
    exe, a.binaries, a.zipfiles, a.datas,
    strip=False, upx=True, upx_exclude=[],
    name='TwinStar_Quantum',
)
